[build]
command = "npx expo export -p web"
functions = "netlify/functions"
publish = "dist"

[[redirects]]
from = "/*"
to = "/.netlify/functions/server"
status = 404

[functions]
included_files = ["dist/**/*"]

[[headers]]
for = "/dist/_expo/functions/*"
[headers.values]
"Cache-Control" = "public, max-age=60, s-maxage=60"
